
GET http://localhost:3000/api/restaurant
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg1NjYzNTBkLWE2MTMtNGFlNi1iM2Y0LWU5NzgyNjRjMTMyMyIsImVtYWlsIjoiam9obnNzLmRvZW5ldEBleGFtcGxlLmNvbSIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc5MDY4MDIyOCwiZXhwIjoxNzkwNjgxMTI4fQ.-y-A24N4kJdzjqZWRi9oovkd61aJCCveWi4EsANHhMY